[project]
name = 'real-estate-investment-optimization-contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.investment-analyzer]
path = 'contracts/investment-analyzer.clar'
clarity_version = 2
epoch = 2.5

[contracts.portfolio-manager]
path = 'contracts/portfolio-manager.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
